### ISSUE TITLE
Your data are incorrect!

### ISSUE THREAD

**Issue by stanislavlukacik** [beli3ver/WebMUM2#3]
geht nicht mit aktuelles setup https://thomas-leister.de/en/mailserver-debian-stretch/
passwords sind in format {SHA512-CRYPT}$6$wHyJsS[...]

**Comment by beli3ver** [comment]
Das ist auch noch eine Alphaversion hier.
Nichts was fertig ist

**Comment by stanislavlukacik** [comment]
danke, planen Sie das machen? :)

**Comment by beli3ver** [comment]
Ja, gerade ein bisschen viel Los

**Comment by stanislavlukacik** [comment]
es würde toll sein!
